easy_admin:
    site_name: 'SPACE <em style="font-size: 80%;">INVADERS.</em>'
    entities:
#        # List the entity class name you want to manage
        - App\Entity\Company
        - App\Entity\Website
