<?php

namespace App\Controller;

use App\Entity\Company;
use App\Entity\Website;
use App\Form\CompanyType;
use App\Repository\CompanyRepository;
use App\Repository\WebsiteRepository;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\FileSystem\FileSystem;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\File\File;


/**
 * @Route("/company")
 */
class CompanyController extends Controller
{
    /**
     * @Route("/", name="company_index", methods="GET")
     */
    public function index(CompanyRepository $companyRepository): Response
    {
        return $this->render('company/index.html.twig', ['companies' => $companyRepository->findAll()]);
    }

    /**
     * @Route("/new", name="company_new", methods="GET|POST")
     */
    public function new(Request $request): Response
    {
        $company = new Company();
        $form = $this->createForm(CompanyType::class, $company);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            // /**
            //  * @var UploadedFile $file
            //  */
            // $file = $company->getLogo();
            // $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();

            // $file->move(
            //     $this->getParameter('image_directory')
            //     ,$fileName
            // );

            // $company->setLogo($fileName);

            $em = $this->getDoctrine()->getManager();
            $em->persist($company);
            $em->flush();

            return $this->redirectToRoute('company_index');
        }
        

        return $this->render('company/new.html.twig', [
            'company' => $company,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }

    /**
     * @Route("/{id}", name="company_show", methods="GET")
     */
    public function show(Company $company, WebsiteRepository $website): Response
    {
        return $this->render('company/show.html.twig', [
            'company' => $company,
            'site' => $website->findBy(['company' => $company->getId()])
        ]);
    }

    public function showSite($id)
    {
        $website = $this->getDoctrine()
            ->getRepository(Product::class)
            ->find($id);


        $categoryName = $website->getWebsite()->getName();

    }

    /**
     * @Route("/{id}/edit", name="company_edit", methods="GET|POST")
     */
    public function edit(Request $request, Company $company): Response
    {
        $form = $this->createForm(CompanyType::class, $company);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('company_edit', ['id' => $company->getId()]);
        }

        return $this->render('company/edit.html.twig', [
            'company' => $company,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="company_delete", methods="DELETE")
     */
    public function delete(Request $request, Company $company): Response
    {
        if ($this->isCsrfTokenValid('delete'.$company->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($company);
            $em->flush();
        }

        return $this->redirectToRoute('company_index');
    }
}
